# WireMock Profile Configuration
# Configures S3Service to point to WireMock mock server for testing

spring:
  profiles:
    active: wiremock

# AWS S3 Configuration for WireMock
aws:
  s3:
    endpoint-url: http://localhost:4566  # WireMock mock S3 endpoint
    bucket-name: test-bucket
    region: us-east-1
    use-iam-role: false  # Use static credentials for testing
    access-key: test
    secret-key: test

# Logging configuration for debugging
logging:
  level:
    com.lithespeed.hellojava06.service: DEBUG
    software.amazon.awssdk: DEBUG
