spring:
  profiles:
    active: fake-s3
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      