spring:
  banner:
    location: classpath:banner-preprod.txt
  # Disable Flyway for container testing - enable in production
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    location: classpath:db/migration
    url: ${spring.datasource.url}
    schemas: poc048
  datasource:
    url: jdbc:postgresql://${AURORA_CLUSTER_ENDPOINT:localhost}:${DB_PORT:5432}/${DB_NAME:hellojava06}?currentSchema=poc048
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    # For container testing without database
    hikari:
      initialization-fail-timeout: ${DB_INIT_TIMEOUT:1}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: false
  config:
    import: "optional:file:${APPCRUD_DB_CREDS_LOCATION:}, optional:file:${DDLMGR_DB_CREDS_LOCATION:}"

# AWS S3 Configuration - K8s/Helm integrated
aws:
  s3:
    # BOM/Helm will provide these via ConfigMap/Secret
    bucket-name: ${S3_BUCKET_NAME}  # From your BOM provisioning
    region: ${AWS_REGION:us-east-1}
    
    # IAM Role-based access (no hardcoded keys)
    # Your Helm charts should set up IRSA (IAM Roles for Service Accounts)
    use-iam-role: ${AWS_USE_IAM_ROLE:true}
    role-arn: ${AWS_ROLE_ARN:}  # Optional: explicit role ARN
    
    # Connection settings for K8s environment
    connection-timeout: ${S3_CONNECTION_TIMEOUT:10000}
    socket-timeout: ${S3_SOCKET_TIMEOUT:30000}
    max-connections: ${S3_MAX_CONNECTIONS:25}

db:
  credentials:
    file: optional:file:${APPCRUD_DB_CREDS_LOCATION:}